name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Export env variables
      run: |
        APP_VERSION="$(cat ./VERSION)"
        echo 'APP_VERSION='"$APP_VERSION" >> $GITHUB_ENV
        echo 'IMAGE_TAG_LATEST=${{ github.repository_owner }}/mission-control:latest' >> $GITHUB_ENV
        echo 'IMAGE_TAG=${{ github.repository_owner }}/mission-control:'"$APP_VERSION" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --tag $IMAGE_TAG_LATEST --tag $IMAGE_TAG
    - name: Push the Docker image
      run: |
        docker push $IMAGE_TAG
        docker push $IMAGE_TAG_LATEST
